"""migration26

Revision ID: 101e05316dd8
Revises: 5b4b4a2a2a6a
Create Date: 2025-07-13 20:02:41.077408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101e05316dd8'
down_revision: Union[str, None] = '5b4b4a2a2a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'qr_wellcome_message'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'qr_enrollment_online'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'points_credited_whatsapp_offline'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'points_debited_whatsapp_offline'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
