"""migration31

Revision ID: 17bcac8d718e
Revises: 954d22d698da
Create Date: 2025-08-21 15:43:29.778209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bcac8d718e'
down_revision: Union[str, None] = '954d22d698da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_contests',
    sa.Column('promo_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contest_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('promo_id')
    )
    op.create_table('promo_check_participation',
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('promo_id', sa.BigInteger(), nullable=True),
    sa.Column('participation_number', sa.String(), nullable=True),
    sa.Column('check_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('amount_initial', sa.BigInteger(), nullable=True),
    sa.Column('amount_effective', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'annulled', name='status'), nullable=True),
    sa.Column('annul_reason', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('annulled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['client_purchases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_contests.promo_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participation_id'),
    sa.UniqueConstraint('participation_number')
    )
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'promo_message'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.drop_table('promo_check_participation')
    op.drop_table('promo_contests')
    # ### end Alembic commands ###
