"""migration22

Revision ID: 2045d342a502
Revises: 0cea26210d94
Create Date: 2025-05-15 00:49:12.656876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2045d342a502'
down_revision: Union[str, None] = '0cea26210d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_bonus_points', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.add_column('client_bonus_points', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
