"""migrataion16

Revision ID: 2428322ffd52
Revises: 487b13bb8bf7
Create Date: 2025-04-12 11:37:53.680201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2428322ffd52'
down_revision: Union[str, None] = '487b13bb8bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_headers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.UUID(), nullable=True),
    sa.Column('period', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('checks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('revenue_data', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_data', sa.Column('period', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('age_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey'),
    sa.UniqueConstraint('vacancies_id', name='vacancies_vacancies_id_key')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.drop_table('revenue_headers')
    # ### end Alembic commands ###
