"""migration28

Revision ID: 2c50c075fa12
Revises: cfaeafa87a60
Create Date: 2025-07-13 22:12:41.801572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c50c075fa12'
down_revision: Union[str, None] = 'cfaeafa87a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_log', 'event_type',
                    existing_type=sa.INTEGER(),
                    type_=sa.Enum('qr_enrollment_offline', 'qr_enrollment_online', 'points_credited_email', 'points_debited_email', 'points_credited_whatsapp', 'points_credited_whatsapp_offline', 'points_debited_whatsapp', 'points_debited_whatsapp_offline', 'points_future_credit_email', 'points_future_debit_email', 'qr_wellcome_message', name='eventtype'),
                    existing_nullable=True,
                    postgresql_using="""
            CASE event_type
                WHEN 1 THEN 'qr_enrollment_offline'
                WHEN 2 THEN 'qr_enrollment_online'
                WHEN 3 THEN 'points_credited_email'
                WHEN 4 THEN 'points_debited_email'
                WHEN 5 THEN 'points_credited_whatsapp'
                WHEN 6 THEN 'points_credited_whatsapp_offline'
                WHEN 7 THEN 'points_debited_whatsapp'
                WHEN 8 THEN 'points_debited_whatsapp_offline'
                WHEN 9 THEN 'points_future_credit_email'
                WHEN 10 THEN 'points_future_debit_email'
                WHEN 11 THEN 'qr_wellcome_message'
            END::eventtype
        """)
    op.execute("ALTER TABLE message_template RENAME COLUMN even_type TO event_type;")
    #op.add_column('message_template', sa.Column('event_type', sa.Enum('qr_enrollment_offline', 'qr_enrollment_online', 'points_credited_email', 'points_debited_email', 'points_credited_whatsapp', 'points_credited_whatsapp_offline', 'points_debited_whatsapp', 'points_debited_whatsapp_offline', 'points_future_credit_email', 'points_future_debit_email', 'qr_wellcome_message', name='eventtype'), nullable=True))
    #op.drop_column('message_template', 'even_type')
    #op.create_foreign_key(None, 'probation_period_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.add_column('message_template', sa.Column('even_type', postgresql.ENUM('qr_enrollment_offline', 'qr_enrollment_online', 'points_credited_email', 'points_debited_email', 'points_credited_whatsapp', 'points_debited_whatsapp', 'qr_wellcome_message', 'points_credited_whatsapp_offline', 'points_debited_whatsapp_offline', 'points_future_credit_email', 'points_future_debit_email', name='eventtype'), autoincrement=False, nullable=True))
    op.drop_column('message_template', 'event_type')
    op.alter_column('message_log', 'event_type',
               existing_type=sa.Enum('qr_enrollment_offline', 'qr_enrollment_online', 'points_credited_email', 'points_debited_email', 'points_credited_whatsapp', 'points_credited_whatsapp_offline', 'points_debited_whatsapp', 'points_debited_whatsapp_offline', 'points_future_credit_email', 'points_future_debit_email', 'qr_wellcome_message', name='eventtype'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    # ### end Alembic commands ###
