"""Move warehouse/org fields from Revenue to RevenueHeaders

Revision ID: 2c85281576a7
Revises: d2391a5ca8eb
Create Date: 2026-01-12 22:30:13.000750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c85281576a7'
down_revision: Union[str, None] = 'd2391a5ca8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('vacancies')
    # op.drop_table('tokens')
    # op.drop_table('resumes')
    op.add_column('revenue_headers', sa.Column('warehouse_name', sa.String(), nullable=True))
    op.add_column('revenue_headers', sa.Column('warehouse_id', sa.UUID(), nullable=True))
    op.add_column('revenue_headers', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('revenue_headers', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE revenue_headers h
        SET
            warehouse_name = d.warehouse_name,
            warehouse_id = d.warehouse_id,
            organization = d.organization,
            organization_id = d.organization_id
        FROM revenue_data d
        WHERE h.document_id = d.document_id
    """)
    # Удаление столбцов с каскадным удалением зависимостей
    op.execute("""
        ALTER TABLE revenue_data DROP COLUMN warehouse_id CASCADE;
    """)
    op.execute("""
        ALTER TABLE revenue_data DROP COLUMN organization CASCADE;
    """)
    op.execute("""
        ALTER TABLE revenue_data DROP COLUMN warehouse_name CASCADE;
    """)
    op.execute("""
        ALTER TABLE revenue_data DROP COLUMN organization_id CASCADE;
    """)

    # op.drop_column('revenue_data', 'warehouse_id')
    # op.drop_column('revenue_data', 'organization')
    # op.drop_column('revenue_data', 'warehouse_name')
    # op.drop_column('revenue_data', 'organization_id')

    # op.alter_column('revenue_headers', 'count_returns',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_server_default=sa.text('0'))
    # op.alter_column('revenue_headers', 'amount_with_vat_returns',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=True,
    #            existing_server_default=sa.text('0.00'))
    # op.alter_column('revenue_headers', 'amount_without_vat_returns',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=True,
    #            existing_server_default=sa.text('0.00'))
    # op.create_unique_constraint(None, 'users_temp', ['id_staff'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users_temp', type_='unique')
    # op.alter_column('revenue_headers', 'amount_without_vat_returns',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False,
    #            existing_server_default=sa.text('0.00'))
    # op.alter_column('revenue_headers', 'amount_with_vat_returns',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False,
    #            existing_server_default=sa.text('0.00'))
    # op.alter_column('revenue_headers', 'count_returns',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))

    op.add_column('revenue_data', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('warehouse_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('revenue_headers', 'organization_id')
    op.drop_column('revenue_headers', 'organization')
    op.drop_column('revenue_headers', 'warehouse_id')
    op.drop_column('revenue_headers', 'warehouse_name')

    # op.create_table('resumes',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['vacancies_id'], ['vacancies.id'], name='resumes_vacancies_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    # )
    # op.create_table('tokens',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    # )
    # op.create_table('vacancies',
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('age_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('age_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='vacancies_pkey'),
    # sa.UniqueConstraint('vacancies_id', name='vacancies_vacancies_id_key')
    # )
    # ### end Alembic commands ###
