"""migrataion6

Revision ID: 3c394cc326bb
Revises: a65bd80dbc04
Create Date: 2025-03-24 19:06:47.010852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c394cc326bb'
down_revision: Union[str, None] = 'a65bd80dbc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('users', 'local')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('local', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_for_printing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_art', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_del', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('barcodes',
    sa.Column('barcode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('barcode_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='barcodes_product_id_fkey'),
    sa.PrimaryKeyConstraint('barcode_id', name='barcodes_pkey'),
    sa.UniqueConstraint('barcode_value', name='barcodes_barcode_value_key')
    )
    op.create_table('probation_period_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='probation_period_answers_pkey')
    )
    op.create_table('prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('price_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='prices_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.create_table('param_and_details',
    sa.Column('param_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='param_and_details_product_id_fkey'),
    sa.PrimaryKeyConstraint('param_detail_id', name='param_and_details_pkey')
    )
    # ### end Alembic commands ###
