"""migrataion15

Revision ID: 487b13bb8bf7
Revises: 8220a4ebe3ba
Create Date: 2025-03-27 00:11:29.090030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487b13bb8bf7'
down_revision: Union[str, None] = '8220a4ebe3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cods', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.drop_column('cods', 'phone_number')
    # ### end Alembic commands ###
