"""empty message

Revision ID: 7205d88ad933
Revises: 
Create Date: 2025-03-22 12:53:24.570583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7205d88ad933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'client_purchases', 'clients', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'client_purchases_return', 'clients', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('clients_mailing', sa.Column('phone', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clients_review', 'clients', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'purchases_return', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('purchases_return', 'is_return')
    op.add_column('users', sa.Column('position_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_bin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users_temp', ['id_staff'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_temp', type_='unique')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'organization_bin')
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'position_id')
    op.drop_column('users', 'position_name')
    op.add_column('purchases_return', sa.Column('is_return', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchases_return', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'clients_review', type_='foreignkey')
    op.drop_column('clients_mailing', 'phone')
    op.drop_constraint(None, 'client_purchases_return', type_='foreignkey')
    op.drop_constraint(None, 'client_purchases', type_='foreignkey')
    op.create_table('probation_period_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='probation_period_answers_pkey')
    )
    op.create_table('param_and_details',
    sa.Column('param_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='param_and_details_product_id_fkey'),
    sa.PrimaryKeyConstraint('param_detail_id', name='param_and_details_pkey')
    )
    op.create_table('barcodes',
    sa.Column('barcode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('barcode_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='barcodes_product_id_fkey'),
    sa.PrimaryKeyConstraint('barcode_id', name='barcodes_pkey'),
    sa.UniqueConstraint('barcode_value', name='barcodes_barcode_value_key')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('price_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('param_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='prices_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_for_printing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_art', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_del', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name='products_pkey')
    )
    op.create_table('reg_temp',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('state_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('telegram_id', name='reg_temp_pkey')
    )
    op.create_table('access_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='access_users_pkey')
    )
    # ### end Alembic commands ###
