"""migration24

Revision ID: 7c760f5e2b19
Revises: 0e28cfa97f7e
Create Date: 2025-06-14 12:08:46.243323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c760f5e2b19'
down_revision: Union[str, None] = '0e28cfa97f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_purchases', sa.Column('site_id', sa.String(), nullable=True))
    op.add_column('client_purchases', sa.Column('mc_id', sa.String(), nullable=True))
    op.drop_column('client_purchases', 'siteId')
    op.drop_column('client_purchases', 'mcId')
    op.add_column('client_purchases_return', sa.Column('site_id', sa.String(), nullable=True))
    op.add_column('client_purchases_return', sa.Column('mc_id', sa.String(), nullable=True))
    op.drop_column('client_purchases_return', 'siteId')
    op.drop_column('client_purchases_return', 'mcId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.add_column('client_purchases_return', sa.Column('mcId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client_purchases_return', sa.Column('siteId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client_purchases_return', 'mc_id')
    op.drop_column('client_purchases_return', 'site_id')
    op.add_column('client_purchases', sa.Column('mcId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client_purchases', sa.Column('siteId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client_purchases', 'mc_id')
    op.drop_column('client_purchases', 'site_id')
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    # ### end Alembic commands ###
