"""migration30

Revision ID: 954d22d698da
Revises: caf161c491b5
Create Date: 2025-08-09 10:16:18.833759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d22d698da'
down_revision: Union[str, None] = 'caf161c491b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE client_purchases RENAME COLUMN mc_id TO ms_id;")
    op.execute("ALTER TABLE client_purchases_return RENAME COLUMN mc_id TO ms_id;")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'points_telegram_debited'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'points_telegram_credited'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.add_column('client_purchases_return', sa.Column('mc_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client_purchases_return', 'ms_id')
    op.add_column('client_purchases', sa.Column('mc_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client_purchases', 'ms_id')
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    # ### end Alembic commands ###
