"""add amount fields to revenue_headers

Revision ID: 95f8a2b1c4d7
Revises: 86d2fc237635
Create Date: 2025-11-07 11:15:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95f8a2b1c4d7'
down_revision: Union[str, None] = '86d2fc237635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_headers', sa.Column('countreturns', sa.Integer(), nullable=True))
    op.add_column('revenue_headers', sa.Column('amountWithVATreturns', sa.NUMERIC(precision=15, scale=2), nullable=True))
    op.add_column('revenue_headers', sa.Column('amountWithoutVATreturns', sa.NUMERIC(precision=15, scale=2), nullable=True))
    op.add_column('revenue_headers', sa.Column('amount_document', sa.NUMERIC(precision=15, scale=2), nullable=True))
    op.add_column('revenue_headers', sa.Column('amount_card', sa.NUMERIC(precision=15, scale=2), nullable=True))
    op.add_column('revenue_headers', sa.Column('amount_certificate', sa.NUMERIC(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenue_headers', 'amount_certificate')
    op.drop_column('revenue_headers', 'amount_card')
    op.drop_column('revenue_headers', 'amount_document')
    op.drop_column('revenue_headers', 'amountWithoutVATreturns')
    op.drop_column('revenue_headers', 'amountWithVATreturns')
    op.drop_column('revenue_headers', 'countreturns')
    # ### end Alembic commands ###
