"""migration32

Revision ID: 9ffe7226765f
Revises: 17bcac8d718e
Create Date: 2025-08-21 17:07:37.893024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffe7226765f'
down_revision: Union[str, None] = '17bcac8d718e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_contests', sa.Column('date_exception', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_contests', 'date_exception')
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.create_table('vacancies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
