"""migration20

Revision ID: a94346a3f325
Revises: cb6dd13e33a3
Create Date: 2025-04-30 22:27:48.976333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94346a3f325'
down_revision: Union[str, None] = 'cb6dd13e33a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_bonus_points', sa.Column('activation_date', sa.DateTime(), nullable=True))
    op.add_column('client_bonus_points', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.drop_column('client_bonus_points', 'expiration_date')
    op.drop_column('client_bonus_points', 'activation_date')
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
