"""migration19

Revision ID: cb6dd13e33a3
Revises: a29353a9f182
Create Date: 2025-04-29 00:01:12.773114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6dd13e33a3'
down_revision: Union[str, None] = 'a29353a9f182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_expiration_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loyalty_program', sa.String(), nullable=True),
    sa.Column('loyalty_program_id', sa.UUID(), nullable=True),
    sa.Column('notify_before_days', sa.BigInteger(), nullable=True),
    sa.Column('message_template', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_bonus_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('loyalty_program', sa.String(), nullable=True),
    sa.Column('loyalty_program_id', sa.UUID(), nullable=True),
    sa.Column('operation_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('row_number', sa.BigInteger(), nullable=True),
    sa.Column('accrued_points', sa.DECIMAL(), nullable=True),
    sa.Column('write_off_points', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('client_purchases_id', sa.String(), nullable=True),
    sa.Column('client_purchases_return_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_purchases_id'], ['client_purchases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    #sa.ForeignKeyConstraint(['client_purchases_return_id'], ['client_purchases_return.return_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_vacation', sa.Column('is_fired', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'probation_period_answers', type_='foreignkey')
    op.create_table('resumes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_table('tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.drop_table('client_bonus_points')
    op.drop_table('bonus_expiration_notifications')
    # ### end Alembic commands ###
