"""Move warehouse/org fields from Revenue to RevenueHeaders

Revision ID: f57ce292a75f
Revises: 19708d2daa51
Create Date: 2025-12-20 01:23:43.374522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f57ce292a75f'
down_revision: Union[str, None] = '19708d2daa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('resumes')
    # op.drop_table('vacancies')
    # op.drop_table('tokens')
    # op.drop_table('users_temp_old')
    op.drop_column('revenue_data', 'warehouse_name')
    op.drop_column('revenue_data', 'organization')
    op.drop_column('revenue_data', 'organization_id')
    op.drop_column('revenue_data', 'warehouse_id')
    op.add_column('revenue_headers', sa.Column('warehouse_name', sa.String(), nullable=True))
    op.add_column('revenue_headers', sa.Column('warehouse_id', sa.UUID(), nullable=True))
    op.add_column('revenue_headers', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('revenue_headers', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE revenue_headers h
        SET
            warehouse_name = d.warehouse_name,
            warehouse_id = d.warehouse_id,
            organization = d.organization,
            organization_id = d.organization_id
        FROM revenue_data d
        WHERE h.document_id = d.document_id
    """)
    # op.alter_column('users', 'staff_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.create_unique_constraint(None, 'users', ['staff_id'])
    # op.drop_column('users', 'local')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('local', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'users', type_='unique')
    # op.alter_column('users', 'staff_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.drop_column('revenue_headers', 'organization_id')
    op.drop_column('revenue_headers', 'organization')
    op.drop_column('revenue_headers', 'warehouse_id')
    op.drop_column('revenue_headers', 'warehouse_name')
    op.add_column('revenue_data', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('revenue_data', sa.Column('warehouse_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.create_table('users_temp_old',
    # sa.Column('id_staff', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('iin', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('date_receipt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('date_dismissal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('update_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('is_fired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('position_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('position_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('organization_bin', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id_staff', name=op.f('users_temp_pkey'))
    # )
    # op.create_table('tokens',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('tokens_pkey'))
    # )
    # op.create_table('vacancies',
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('age_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('age_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='vacancies_pkey'),
    # sa.UniqueConstraint('vacancies_id', name='vacancies_vacancies_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('resumes',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('vacancies_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['vacancies_id'], ['vacancies.id'], name=op.f('resumes_vacancies_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    # )
    # ### end Alembic commands ###
